### ISSUE TITLE
BeaconChain.compute_logical_time/1 -> No case clause matching -2

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#1095]
There's an error where the `rem()` call in `compute_logical_time` returns -2, which is not contemplated in the case clauses.
```
ERROR 10:09:02.001 GenServer LambdaEthereumConsensus.Beacon.BeaconChain terminating

** (CaseClauseError) no case clause matching: -2
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/beacon/beacon_chain.ex:235: LambdaEthereumConsensus.Beacon.BeaconChain.compute_logical_time/1
    (lambda_ethereum_consensus 0.1.0) lib/lambda_ethereum_consensus/beacon/beacon_chain.ex:178: LambdaEthereumConsensus.Beacon.BeaconChain.handle_info/2
    (stdlib 5.2.3) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2.3) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: :on_tick 
panic: listen udp 0.0.0.0:9000: bind: address already in use

goroutine 1 [running]:
libp2p_port/internal/utils.PanicIfError(...)
/libp2p_port/internal/utils/utils.go:19
libp2p_port/internal/discovery.NewDiscoverer(0x40002e43d0?, 0x400023a640, 0x400001be80)
/libp2p_port/internal/discovery/discovery.go:34 +0x45c
main.commandServer()
/libp2p_port/main.go:74 +0x138
main.main()
/libp2p_port/main.go:90 +0x1c

```

**Comment by Arkenan** [comment]
The cause of this issue seems to be the beacon node initializing before the network genesis time. This is a race condition and may happen simply because the node process started too quickly. An option may be to have the first tick happen after genesis time.
